wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.1
    start_time: 1675836895.07894
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.1
      5: 0.13.10
      8:
      - 2
      - 3
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 1.0e-05
num_classes:
  desc: null
  value: 196
weight_decay:
  desc: null
  value: 0.01
zero_init_residual:
  desc: null
  value: false
